baseURL = "/"
author = "Pim Snel"
copyright = "Copyright © 2024, Pim Snel"
paginate = 3.0
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
ignoreErrors = [
  "error-remote-getjson"
]
theme = "Paper"
title = "Not Nix"

[params]
github = "notnix-com"

[markup]

  [markup.goldmark]

    [markup.goldmark.renderer]
    unsafe = true

[menu]

  [[menu.main]]
  identifier = "about"
  name = "About"
  url = "/post/about-notnix/"
  weight = 10.0

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
  disabled = false
  simple = true

  [privacy.twitter]
  disabled = false
  enableDNT = true
  simple = true

  [privacy.instagram]
  disabled = false
  simple = true

  [privacy.youtube]
  disabled = false
  privacyEnhanced = true

[services]

  [services.instagram]
  disableInlineCSS = true

  [services.twitter]
  disableInlineCSS = true
